url: https://ideasdump.github.io/
baseurl: ''
remote_theme: hydecorp/hydejack
markdown: GFM
menu:
  - title: Blog
    url: /blog/
  - title: Projects
    url: /projects/
  - title: Resume
    url: /resume/
  - title: About
    url: /about/

accent_image: 'assets/sidebar-bg.jpg'