remote_theme: hydecorp/hydejack
markdown: kramdown
kramdown:
  math_engine: mathjax

permalink: /blog/:categories/:year-:month-:day-:title/
menu:
  - title: Blog
    url:   /blog/
  - title: Projects
    url:   /projects/
  - title: About
    url:   /about/

accent_image: 'assets/sidebar-bg.jpg'

plugins:
  - jekyll-default-layout
  - jekyll-feed
  - jekyll-optional-front-matter
  - jekyll-paginate
  - jekyll-readme-index
  - jekyll-relative-links
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-titles-from-headings
  - jekyll-include-cache
  - jekyll-last-modified-at

collections:
  featured_categories:
    permalink:         blog/:name/
    output:            true
  featured_tags:
    permalink:         /tag-:name/
    output:            true

paginate:              10
paginate_path:         /blog/:num/