url: https://ideasdump.github.io/
remote_theme: hydecorp/hydejack
markdown: GFM
menu:
  - title: Blog
    url: /blog/
  - title: Projects
    url: /projects/
  - title: Resume
    url: /resume/
  - title: About
    url: /about/

accent_image: 'assets/sidebar-bg.jpg'

plugins:
  - jekyll-default-layout
  - jekyll-feed
  - jekyll-optional-front-matter
  - jekyll-paginate
  - jekyll-readme-index
  - jekyll-relative-links
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-titles-from-headings
  - jekyll-include-cache
  - jekyll-last-modified-at

  